export { createClient } from "./client";
export { createServerClient } from "./server";
export {
  getCurrentUser,
  getIsAdmin,
  getIsSuperAdmin,
  getAdminRole,
  getAdminRoleFromUser,
  getAdminTopicsScope,
  ADMIN_ROLES,
  isSuperAdminRole,
} from "./auth";
export type { AdminRole, AdminTopicsScope } from "./auth";
export {
  getAdminChapters,
  getAdminChapterByKey,
  getTopics,
  getTopicsByChapter,
  getAdminTopicsByChapter,
  canAdminAccessTopic,
  getTopicBySlugAndChapter,
  getTopicMetaById,
  getQuizzes,
  getQuizzesByTopicSlugAndChapter,
  getQuizWithPages,
  getQuizWithPagesBySlug,
  getCrosswordQuizByQuizId,
  getCrosswordQuizBySlug,
  getCrosswordOptions,
  getTheoryBlocks,
} from "./queries";
export type {
  AdminChapter,
  Topic,
  Quiz,
  QuizVideo,
  QuizPage,
  Question,
  Option,
  QuestionWithOptions,
  QuizWithPages,
  QuizPageWithDetails,
  CrosswordDirection,
  CrosswordEntry,
  CrosswordGridCell,
  CrosswordGridSnapshot,
  CrosswordPuzzle,
  CrosswordQuiz,
  TestType,
  TheoryBlock,
  TheoryBlockType,
} from "./types";
